yihong0618/bilingual_book_maker

README-CN.md
README.md

依我的理解，ChatGPT 是 OpenAI 开发的聊天机器人，属于一个产品，它正在使用 GPT 3.5 turbo 模型，未来不排除使用其他模型的可能，比如使用 GPT 4 模型。根据官方博客，GPT-3.5-turbo 是一个 OpenAI 的付费模型中更推荐的主流廉价模型，比其他 GPT 3.5 模型便宜了十倍。IMHO，这样修改文档可以更好澄清用户对 billing 疑惑。

feat: Change documentation on clearifying model usage

---

README.md

This commit updates the Docker command in the README.md file to remove the container keyword and makes the command more concise. Additionally, it adds an example command and uses the abbreviation e.g. for clarity. No functionality has been changed, only the formatting of the command has been updated.

Update Docker command in README.md

---

README-CN.md
README.md
book_maker/cli.py
book_maker/loader/epub_loader.py

没有标签包裹的字符串无法被翻译，此处提供了一个参数可供选择。但是这类epub猜测可能导致排版出现问题，建议实在需要再加入
Strings that are not wrapped in tags cannot be translated, but a parameter is provided here as an option. However, allowing untagged strings in EPUB files may lead to formatting issues. Therefore, it is recommended to use this option only when necessary.

fix(#92): add a arguments to allow NavigableStrings translate

---

README-CN.md
README.md
book_maker/cli.py
book_maker/obok.py

`--book_from <E-READER>` to specify connected e-reader (Only support "kobo" now)
`--device_path <PATH>` to specify path of mounting point
If these two options are specified, `obok.py` would check mounting point
of device, and show a list of available epub files in `/MOUNTING/POINT/.kobo/kepub`
User input the number of book need to be translated, then the decrypted epub
would be save to current directory. And this epub file would be pass to
`epub_loader`.
Usage would be like:
```bash
python make_book.py \                                                                                        1
--model gpt3 \
--language "Traditional Chinese" \
--book_from kobo \
--device_path /run/media/pham/KOBOeReader/
```
Source: https://github.com/apprenticeharper/DeDRM_tools/blob/master/Obok_plugin/obok/ …

Add options for books on kobo e-reader

---

README.md
book_maker/cli.py
book_maker/loader/epub_loader.py
book_maker/loader/helper.py

I feel it looks more comfortable to specify the translated style, hope to support this option , ex:
` --translation_style "color: #808080; font-style: italic;"`
` --translation_style "color: #4a4a4a; font-style: normal; background-color: #f7f7f7; padding: 5px; margin: 10px 0; border-radius: 5px;"`

support --translation_style

---

book_maker/cli.py
book_maker/loader/epub_loader.py

if you only have a few files with translations, please use comma to split them, example: `--only_filelist 'nav.xhtml,cover.xhtml'`
if you have more than one file to exclude, please use comma to split them, example: `--exclude_filelist 'nav.xhtml,cover.xhtml'`
if you have more than one tag to exclude, please use comma to split them, example: `--exclude_filelist 'table,sup'`
related issue: https://github.com/yihong0618/bilingual_book_maker/issues/210 https://github.com/yihong0618/bilingual_book_maker/issues/191

support exclude or only translate filelist, exclude taglist

---

.github/workflows/make_test_ebook.yaml
Makefile
setup.py
tests/test_integration.py

#192
1. refactor the test flow into unittests
2. add a Makefile for local test
Since I don't have api permission, @yihong0618 could you help me test the Makefile?
I notice that the packages in requirements.txt and install_requires are not consistent, so I add a fix here. If @yihong0618 you are intend to let this happen, I can delete the fix.
1. Add linter like pylint or flake in both Makefile and github workflow
https://github.com/yihong0618/bilingual_book_maker/blob/45bfdf7907518b0579313560af80323e7f1e9b55/book_maker/obok.py#L264
I noticed that this package imported in source code but not listed in requirements.txt. Add linter may avoid this bug.
2. Break the github workflow
github workflow can break into "linter" and "tests".
"linter" can include isort, black, autoflake, which can …

MakeFile easy to test local

---

book_maker/translator/google_translator.py

Improved the issue of Google Translate skipping paragraphs due to network problems by increasing the number of attempts (defaulting to 3 attempts).

Google Translate skipping paragraphs

---

Dockerfile

Dockerfile中复制了requirements.txt，但文件的内容是`-e .`，需要同时复制setup.py才能正常构建镜像。

fix(dockerfile): bug fix for building Docker image

---

book_maker/loader/epub_loader.py

Two bugs are found when using the exlude_filelist and only_filelist options:
1. progress bars: currently the progress bar adds up the tags for all files in an epub; after the commit it only counts tags in files that will be included.
2. temp file that only translate a subset of files will lead to a mismatch between translated texts and original texts. The commit fixes the bug.

fix: bugs for using exlude_filelists and only_filelists

---

.github/workflows/docs.yaml

This action generate a branch called "gh-pages". Everytime when a new pull request is merged to main, this branch will auto-update and publish latest documentation.
This works in my forked repo. https://yylizh.github.io/bilingual_book_maker/
ref: https://github.com/yihong0618/bilingual_book_maker/pull/319

Github actions for deploy doc page

---

book_maker/cli.py
book_maker/loader/epub_loader.py

Known issue:  some text is not replaced with translation
I'm really not familiar with BS, please have a look

Feat: combine multiple lines into one block, add a new option --block_size

---

book_maker/translator/chatgptapi_translator.py

I was receiving the following error when attempting to translate with GPT4. Fixed for me by removing gpt-4-0314 from model list.
> Error code: 404 - {'error': {'message': 'The model `gpt-4-0314` has been deprecated, learn more here:
> https://platform.openai.com/docs/deprecations', 'type': 'invalid_request_error', 'param': None, 'code':
> 'model_not_found'}}

remove gpt-4-0314 from model list

---

book_maker/loader/helper.py
requirements.txt
setup.py

sometimes the translating progress would be interrupted by API failure, but after resuming, I get a confusing result about the output #386
This PR append default backoff policy for translation, it would relieve that issue.

chore: setup default backoff for tranlate method

---

README.md
book_maker/cli.py
book_maker/translator/__init__.py
book_maker/translator/chatgptapi_translator.py

This is in response to https://github.com/yihong0618/bilingual_book_maker/issues/390. 
```
--model openai --model_list gpt-4-1106-preview
--model openai --model_list gpt-4-1106-preview,gpt-3.5-turbo-0125
```
Currently this `openai` model alias is only for this behavior, but I think it should be expanded to be the defacto way to use the OpenAI API. The current approach is a bit messy because `chatgptapi` and `gpt-4` are two separate top-level models.
I opted to add a new `model` to preserve backwards compatibility, but also paves a path for future CLI improvements.
We should probably include some automatic checking to make sure all the models you specify are valid, but since we're using `cycle()`, this failure should be found within the first `N` paragraphs.

Add a model named "openai" and "--model_list" option

---

README.md

This PR updates the `README.md` file to reflect recent changes made in the `cli.py` file. The following updates have been made:
1. **Model Options:**
- Added `GPT4omini` as an option for the `--model` parameter.
- Clarified that the `--use_context` option is available for all ChatGPT-compatible models, not just `GPT4`.
2. **New Parameters:**
- Introduced the `--context_paragraph_limit` parameter to set a limit on the number of context paragraphs when using the `--use_context` option.
- Added the `--temperature` parameter to set the temperature for `chatgptapi`/`gpt4`/`claude` models.
- Added the `--block_size` parameter to merge multiple paragraphs into one block, which can increase accuracy and speed up the process but may disturb the original format. This must be used with …

doc: improve the doc cli

---

book_maker/cli.py
book_maker/config.py
book_maker/loader/epub_loader.py
book_maker/translator/chatgptapi_translator.py

This PR implements functionality that significantly improves the efficiency of the EPUB translation process by utilizing ChatGPT's batch API. The main changes are as follows:
1. **Implementation of Batch Translation Feature**
- `--batch` option: Batch process translations using ChatGPT's batch API
- `--batch-use` option: Create files using pre-generated batch translation results
2. **Batch Processing Workflow**
- Creation and management of batch requests
- Execution of batch jobs and status checking
- Retrieval and processing of batch results
1. **Initialization**
- Initial setup for batch processing with the `batch_init` method
- Sanitization of book names
2. **Creation of Translation Queue**
- Add texts to be translated to the queue using the `add_to_batch_translate_queue` method
3. …

supprt openai batch api

---

book_maker/cli.py

Instead of showing an ugly crash message like the one below to the user when they don't provide any arguments, it would be better to display a more user-friendly message:
```
❯ bbook_maker
Traceback (most recent call last):
File "/Users/xyb/.virtualenvs/bilingual_book_maker/bin/bbook_maker", line 8, in <module>
sys.exit(main())
^^^^^^
File "/Users/xyb/projects/bilingual_book_maker/book_maker/cli.py", line 328, in main
if not os.path.isfile(options.book_name):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
A more appropriate message would be:
```
❯ bbook_maker
Error: please provide the path of your book using --book_name <path>
```

Avoid crash if not provide book_name

---

book_maker/translator/claude_translator.py

Support for setting temperature with Claude was added in #278 but then lost in 70d2535f84de75d6460096ccf2ea64d1af9710e0. This adds back support for setting temperature with Claude.
It also updates the default model for Claude to the latest Claude 3.5 Sonnet model, which is much better at translating books than the old Claude 3 Haiku model.

Fix claude temperature and update model

---

book_maker/cli.py
book_maker/loader/epub_loader.py
book_maker/loader/srt_loader.py
book_maker/loader/txt_loader.py

I noticed that the `--context_paragraph_limit` option does not get passed through to the translator, and will always default to 3 (from config.py) without this change.

Pass --context_paragraph_limit option from CLI

---

book_maker/translator/google_translator.py

For some reason, currently the Google translator hard-coded the target language (the language to be translated to) to Chinese. This PR fixes this and dynamically embeds the language code in the URL.

Use dynamic language in Google translator
