yihong0618/bilingual_book_maker

- .gitignore
- README.md
> [bugfix] fix readme

- make_book.py
change target language to the language option.
> fix: invalid target language when TIME LIMIT

- make_book.py
- Removed unnecessary casts
- Made a sum comprehension on `all_p_length`
> Refactor on logic

- .dockerignore
- Dockerfile
- README.md
We can use [Docker](https://www.docker.com/) if we don't want to deal with setting up the environment.
> use docker

- make_book.py
Fix the bug caused by parsing non-HTML files
修复由于解析非html文件出现的bug
> fix(#57): Fix the bug caused by parsing non-HTML files

- book_maker/loader/epub_loader.py
> [bugfix] Fix the wrong typesetting of the generated temporary files

- README.md
- book_maker/cli.py
- book_maker/loader/epub_loader.py
- book_maker/translator/__init__.py
- book_maker/translator/google_translator.py
added google translate, _translate to_ language only support `zh-CN`
> feat: added google translate support

- book_maker/translator/chatgptapi_translator.py
- Extracted get_translation method to improve code readability and maintainability
- Moved the code that handles API key and completion creation to the new method
(No functional changes, just extracted a function and added some comments to wait for improvement)
> refactor(translator): extract get_translation method

- .github/workflows/make_test_ebook.yaml
- README-CN.md
- README.md
- book_maker/loader/__init__.py
- book_maker/loader/txt_loader.py
- test_books/the_little_prince.txt
主要参考 https://github.com/yihong0618/bilingual_book_maker/pull/35 实现txt loader。
目前用the_little_prince.txt 测试，效果正常。
TODO：
> feat: add txt book loader

- README-CN.md
- README.md
- Remove the duplicate item [13,17] => [17] in README
- Correct the item numbers in README
- Fix typo
- Add 示范用例 section title in the Chinese README to match the English README
> Improving the READMEs

- .github/workflows/make_test_ebook.yaml
- README-CN.md
- README.md
- book_maker/cli.py
- book_maker/loader/epub_loader.py
- book_maker/loader/txt_loader.py
batch translate txt file. (I'm not sure if it would be better to let the user decide on the batch size. default batchSize 10)
> feat: batch translate txt file

- README-CN.md
- README.md
These contents have already appeared above.
> Delete duplicate description

- book_maker/utils.py
> feat: add target language

- README-CN.md
- README.md
- book_maker/cli.py
- book_maker/loader/epub_loader.py
- book_maker/loader/txt_loader.py
- book_maker/translator/base_translator.py
- book_maker/translator/chatgptapi_translator.py
[Quickstart: Get started using ChatGPT (preview) and GPT-4 (preview) with Azure OpenAI Service](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference)
> feat: add Azure OpenAI service support

- README-CN.md
> README-CN.md里增加操作视频

- book_maker/loader/epub_loader.py
> Fixes #109

- book_maker/translator/chatgptapi_translator.py
> 替 BBM_CHATGPTAPI_SYS_MSG 與 BBM_CHATGPTAPI_USER_MSG_TEMPLATE 加入斷行能力

- book_maker/translator/chatgptapi_translator.py
> Add some color on the translated text output

- book_maker/cli.py
- book_maker/loader/epub_loader.py
- book_maker/loader/helper.py
- book_maker/loader/txt_loader.py
related
https://github.com/yihong0618/bilingual_book_maker/issues/231
https://github.com/yihong0618/bilingual_book_maker/issues/214
https://github.com/yihong0618/bilingual_book_maker/issues/170
https://github.com/yihong0618/bilingual_book_maker/issues/169
support `--single_translate` in epub
> support single_translate in epub

- book_maker/loader/__init__.py
- book_maker/loader/srt_loader.py
- test_books/Lex_Fridman_episode_322.srt
增加srt字幕的支持。支持 --accumulated_num参数。
> add srt support

- book_maker/loader/srt_loader.py
- book_maker/loader/txt_loader.py
https://github.com/yihong0618/bilingual_book_maker/issues/252
> feat: support single_translate for txt & srt

- README-CN.md
- README.md
- book_maker/cli.py
- book_maker/translator/__init__.py
- book_maker/translator/claude_translator.py
* Support Anthropic's [Claude](https://console.anthropic.com/docs) model.
* By the way, fixed the incorrect deepl call method in the documentation.
> feat: support claude model

- book_maker/cli.py
- book_maker/loader/epub_loader.py
- book_maker/loader/srt_loader.py
- book_maker/loader/txt_loader.py
- book_maker/translator/chatgptapi_translator.py
- book_maker/translator/claude_translator.py
- book_maker/translator/gpt3_translator.py
- book_maker/translator/gpt4_translator.py
- add `temperature` parameter to `ChatGPTAPI`/`GPT3`/`GPT4`/`Claude`
- add `temperature` parameter to book loaders
- add `--temperature` option to cli
> feat: add temperature parameter

- .github/workflows/make_test_ebook.yaml
- book_maker/loader/epub_loader.py
- book_maker/translator/caiyun_translator.py
and bring back old test
its easy to check
> fix: #280,#279

- README.md
- book_maker/translator/litellm_translator.py
- setup.py
This PR adds support for models from all the above mentioned providers using https://github.com/BerriAI/litellm/
Here's a sample of how it's used:
```
from litellm import completion, acompletion
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"
messages = [{ "content": "Hello, how are you?","role": "user"}]
response = completion(model="gpt-3.5-turbo", messages=messages)
model_name = "replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1"
response = completion(model_name, messages)
response = completion("command-nightly", messages)
response = completion(model="claude-instant-1", messages=messages)
```
> Add support for Llama2, Palm, Cohere, Replicate Models - using litellm

- README-CN.md
- README.md
- book_maker/cli.py
- book_maker/translator/deepl_translator.py
- docs/model_lang.md
Required action due to copyright considerations
> Change links to deepl

- README-CN.md
- README.md
- book_maker/cli.py
- book_maker/translator/__init__.py
- book_maker/translator/custom_api_translator.py
- docs/model_lang.md
This PR allows users to use their own translation API.
Currently compatible with [DeepLX](https://github.com/OwO-Network/DeepLX) and [openai-translate](https://github.com/missuo/openai-translate). It can also support **deeplx** written by [zu1k](https://github.com/zu1k).
> feat: support for Custom API

- book_maker/translator/custom_api_translator.py
> Fix misplaced target_lang

- book_maker/translator/chatgptapi_translator.py
1. when I use azure openai will get "api_base" not  have this arribute error. 
So I add `         self.api_base = api_base`
2. In line 84 when the message content type is None will get typeError.
So I add a if else ”ifelse process“ to avoid this error.
> Fixed Azure openai bug

- README-CN.md
- README.md
- book_maker/translator/__init__.py
- book_maker/translator/tencent_transmart_translator.py
> feat: support Tencent TranSmart

- book_maker/cli.py
- book_maker/translator/chatgptapi_translator.py
How to use:
```
ollama server
```
```
python make_book.py --book_name test_books/animal_farm.epub  --ollama_model qwen:7b
```
> add ollama support

- book_maker/cli.py
- book_maker/translator/__init__.py
- book_maker/translator/chatgptapi_translator.py
- docs/model_lang.md
> feat: support model gpt4o-mini

- Dockerfile
Hi, I found that `setup.py` was deleted in commit e7ae81e The Dockerfile should also be modified.
> fix(docker): update Dockerfile to copy only requirements.txt

- book_maker/translator/chatgptapi_translator.py
**Improved Paragraph Translation Integrity with Structured Prompts**
This PR enhances the paragraph translation reliability by implementing structured prompts and robust extraction patterns to maintain 1:1 alignment between original and translated paragraphs.
**Key Changes:**
1. **Structured Translation Prompts**  
- Added explicit paragraph numbering in prompts (e.g., `PARAGRAPH 1: [...]`)
- Implemented strict response format requirements for translations
- Added validation for paragraph count matching
2. **Enhanced Translation Extraction**  
- Created regex patterns for structured response parsing
- Added fallback extraction methods for error resilience
- Implemented paragraph count validation and padding
3. **Prompt Engineering Improvements**  
- Added clear formatting instructions to …
> fix: Fix translation paragraph count mismatch by explicitly instructing LLM about paragraph requirements
